sensor:
  - platform: rest
    name: air_france_7730
    resource: http://api.aviationstack.com/v1/flights
    scan_interval: 900
    params:
      access_key: !secret aviation_stack_apikey
      flight_iata: af7730
      limit: 1
    value_template: "{{ value_json['data'][0]['flight_status'] }}"
    json_attributes_path: '$.data.[0].arrival'
    json_attributes:
      - delay
      - scheduled
      - estimated
      - actual
