mqtt:
  sensor:
  - unique_id: rf433_temp
    device_class: temperature
    state_class: measurement
    state_topic: homie/rf-sockets-salon/temperature/degrees
    name: "RF 433 MHz - Temperature"
    unit_of_measurement: "°C"

  - unique_id: rf433_vcc
    device_class: battery
    state_topic: homie/rf-sockets-salon/powerSupply/powerSupply
    name: "RF 433 MHz - alim"
    unit_of_measurement: "mV"

  - unique_id: rf433_wifi
    device_class: signal_strength
    state_topic: homie/rf-sockets-salon/$stats/signal
    name: "RF 433 MHz - Signal WiFi"
    unit_of_measurement: "%"

  - device_class: illuminance
    state_class: measurement
    state_topic: homie/rf-sockets-salon/brightness/adc_1024
    name: "RF 433 MHz - luminosité"
    unit_of_measurement: "int10"

  switch:
  - name: sw1
    command_topic: "homie/rf-sockets-salon/switches_1/on/set"
    state_topic: "homie/rf-sockets-salon/switches_1/on"
    availability_topic: "homie/rf-sockets-salon/$state"
    payload_on: "on"
    payload_off: "off"
    payload_available: "ready"
    payload_not_available: "lost"

  - name: sw2
    command_topic: "homie/rf-sockets-salon/switches_2/on/set"
    state_topic: "homie/rf-sockets-salon/switches_2/on"
    availability_topic: "homie/rf-sockets-salon/$state"
    payload_on: "on"
    payload_off: "off"
    payload_available: "ready"
    payload_not_available: "lost"

  - name: sw3
    command_topic: "homie/rf-sockets-salon/switches_3/on/set"
    state_topic: "homie/rf-sockets-salon/switches_3/on"
    availability_topic: "homie/rf-sockets-salon/$state"
    payload_on: "on"
    payload_off: "off"
    payload_available: "ready"
    payload_not_available: "lost"

  - name: sw4
    command_topic: "homie/rf-sockets-salon/switches_4/on/set"
    state_topic: "homie/rf-sockets-salon/switches_4/on"
    availability_topic: "homie/rf-sockets-salon/$state"
    payload_on: "on"
    payload_off: "off"
    payload_available: "ready"
    payload_not_available: "lost"

  - name: sw5
    command_topic: "homie/rf-sockets-salon/switches_5/on/set"
    state_topic: "homie/rf-sockets-salon/switches_5/on"
    availability_topic: "homie/rf-sockets-salon/$state"
    payload_on: "on"
    payload_off: "off"
    payload_available: "ready"
    payload_not_available: "lost"

