  les décorations de Noël:
    - light.sapin
    - light.guirlandes_baies_vitrees
    - light.guirlande_a_boules
    - light.guirlande_buffet
    - light.village_de_noel

  les guirlandes de Noël:
    - light.sapin
    - light.guirlandes_baies_vitrees
    - light.guirlande_a_boules
    - light.guirlande_buffet

