- platform: history_stats
  name: Présence chambre parents quotidienne
  entity_id: binary_sensor.long_term_parents_bedroom_presence
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  duration:
    hours: 24

- platform: template
  sensors:
    presence_chambre_as_integer:
      friendly_name: "Compteur de déclenchement de présence chambre parents"
      unit_of_measurement: 'pings'
      value_template: >-
        {{ states('counter.presence_chambre') | int }}
